import math
bill_amount = float(input("Enter your total bill"))
country = str(input("Which country are you currently in?"))

non_tippers = [
"Australia",
"Belgium",
"Colombia", 
"Cyprus",
"Fiji",
"Georgia",
"Italy",
"Jamaica",
"Malaysia",
"New Zealand",
"Norway",
"Portugal",
"Samoa",
"South Korea",
"Switzerland",
"Tonga",
"Uganda"
    ]

rule = {
"China":"do not tip, as this is considered disrespectful",
"Japan":"do not tip, as this is considered disrespectful",
"Hong Kong":"do not tip, as this is considered disrespectful",
"Denmark":"Service charge is usually included in the bill",
"Singapore":"Service charge is usually included in the bill",
"Finland":"round up your bill out of courtesy",
"Maldives":"round up or leave the change",
"France":"Service charge is included in the bill as a legal requirement",
"Netherlands":"Service charge is included in the bill as a legal requirement",
"United Kingdom":"no tip is required, as tipping culture isn't very big in the UK but tips are always appreciated as a sign of good service"
}

rounders = ["Maldives", "Finland"]

five_percenters = [
"Austria",
"Bangladesh",
"Cambodia",
"Ecuador",
"Greece",
"Indonesia",
"Jordan",
"Malta",
"Mauritius", 
"Nepal",
"Sweden",
"Tanzania", 
"Turkey",
"Vietnam",
]
ten_percenters = [
"Argentina",
"Bahamas",
"Barbados", 
"Bulgaria", 
"Chile",
"Costa Rica",
"Croatia",
"Cuba",
"Czechia",
"Dominican Republic",
"Egypt",
"Germany",
"Hungary",
"Iceland",
"India",
"Ireland",
"Israel", 
"Kenya",
"Madagascar",
"Pakistan",
"Panama",
"Poland",
"Mexico", 
"Morocco", 
"Peru", 
"Philippines", 
"Qatar"
"Thailand",
"Taiwan",
"Tunisia", 
"Ukraine"
]
fifteen_percenters = [
"Belize",
"Canada (English)",
"Canada (French)",
"Monaco",
"United States of America"
]

currencySign = {
"Australia":"$",
"Belgium":"€",
"Cyprus":"€",
"Italy":"€",
"Jamaica":"$",
"New Zealand":"$",
"Norway":"kr",
"Portugal":"€",
"Samoa":"T",
"South Korea":"₩",
"Tonga":"T$",
"Uganda":"Sh",
"China":"¥",
"Hong Kong":"$",
"Denmark":"kr",
"Singapore":"$",
"Finland":"€",
"Maldives":"ރ.",
"France":"€",
"Netherlands":"€",
"United Kingdom":"£",
"Austria":"€",
"Bangladesh":"৳",
"Cambodia":"៛",
"Greece":"€",
"Indonesia":"Rp",
"Jordan":"د.ا",
"Mauritius":"Rs", 
"Nepal":"Rs",
"Sweden":"kr",
"Tanzania":"Sh", 
"Vietnam":"₫",
"Argentina":"$",
"Bahamas":"$",
"Barbados":"$", 
"Bulgaria":"лв", 
"Costa Rica":"₡",
"Croatia":"Kn",
"Cuba":"$",
"Czech Republic":"Kč",
"Dominican Republic":"$",
"Egypt":"£",
"Germany":"€",
"Hungary":"Ft",
"Iceland":"Kr",
"India":"₹",
"Ireland":"€",
"Israel":"₪", 
"Kenya":"Sh",
"Madagascar":"Ar",
"Pakistan":"Rs",
"Panama":"B/.",
"Poland":"zł",
"Mexico":"$", 
"Morocco":"د.م.", 
"Peru":"S/.",
"Philippines":"₱", 
"Qatar":"ر.ق",
"Thailand":"฿",
"Tunisia":"د.ت", 
"Ukraine":"₴",
"Belize":"$",
"Canada (English)":"$",
"Canada (French)":"$",
"Monaco":"€",
"UAE":"د.إ	",
"Afghanistan":"Af",
"Albania":"L",
"Armenia":"Դ",
"Angola":"Kz",
"Aruba":"ƒ",
"Azerbaijan":"ман",
"Bosnia and Herzegovina":"KM",
"Bahrain":"ب.د",
"Burundi":"₣",
"Bermuda":"$",
"Brunei":"$",
"Bolivia":"Bs.",
"Brazil":"R$",
"Bhutan":"Nu",
"Botswana":"P",
"Belarus":"Br",
"Congo":"₣",
"Switzerland":"₣",
"Lichtenstein":"₣",
"Chile":"$",
"Colombia":"$",
"Cape Verde":"$",
"Djibouti":"₣",
"Algeria":"د.ج",
"Eritrea":"Nfk",
"Ethiopia":"Br",
"Andorra":"€",
"Estonia":"€",
"Kosovo":"€",
"Latvia":"€",
"Lithuania":"€",
"Luxembourg":"€",
"Malta":"€",
"Montenegro":"€",
"San-Marino":"€",
"Slovakia":"€",
"Slovenia":"€",
"Spain":"€",
"Vatican":"€",
"Fiji":"$",
"Georgia":"ლ",
"South Ossetia":"p.",
"Ghana":"₵",
"Gibraltar":"£",
"Gambia":"D",
"Guinea":"₣",
"Guatemala":"Q",
"Guyana":"$",
"Honduras":"L",
"Haiti":"G",
"Palestine":"₪",
"Iraq":"ع.د",
"Iran":"﷼",
"Japan":"¥",
"Kyrgyzstan":"лв",
"North Korea":"₩",
"Kuwait":"د.ك",
"Cayman Islands":"$",
"Kazakhstan":"〒	",
"Laos":"₭",
"Lebanon":"ل.ل",
"Sri Lanka":"Rs",
"Liberia":"$",
"Lesotho":"L",
"Libya":"ل.د",
"Moldova":"L",
"Macedonia":"ден",
"Myanmar":"K",
"Mongolia":"₮",
"Macao":"P",
"Mauritania":"UM",
"Malawi":"MK",
"Malaysia":"RM",
"Mozambique":"MTn",
"Namibia":"$",
"Nigeria":"₦",
"Nicaragua":"C$",
"Cook Islands":"$",
"Niue":"$",
"Pitcairn Island":"$",
"Oman":"ر.ع.",
"Papua New Guinea":"K",
"Paraguay":"₲",
"Romania":"L",
"Kosovo":"din",
"Serbia":"din",
"Russia":"p.",
"Rwanda":"₣",
"Saudi Arabia":"ر.س",
"Solomon Islands":"$",
"Seychelles":"Rs",
"Sudan":"£",
"Ascension Island":"£",
"Saint Helena":"£",
"Tristan da Cunha":"£",
"Sierra Leone":"Le",
"Somalia":"Sh",
"Suriname":"$",
"Sao Tome and Principe":"Db",
"Syria":"ل.س",
"Swaziland":"L",
"Tajikistan":"SM",
"Turkmenistan":"m",
"North Cyprus":"₤",
"Turkey":"₤",
"Trinidad and Tobago":"$",
"Taiwan":"$",
"American Samoa":"$",
"British Indian Ocean Territory":"$",
"British Virgin Islands":"$",
"Guam":"$",
"Haiti":"$",
"Marshall Islands":"$",
"Micronesia":"$",
"Northern Mariana Islands":"$",
"Pacific Remote islands":"$",
"Palau":"$",
"Panama":"$",
"Puerto Rico":"$",
"Turks and Caicos Islands":"$",
"United States of America":"$",
"US Virgin Islands":"$",
"Benin":"₣",
"Burkina Faso":"₣",
"Cameroon":"₣",
"Central African Republic":"₣",
"Chad":"₣",
"Congo (Brazzaville)":"₣",
"Côte d'Ivoire":"₣",
"Equatorial Guinea":"₣",
"Gabon":"₣",
"Guinea-Bissau":"₣",
"Mali":"₣",
"Niger":"₣",
"Senegal":"₣",
"Togo":"₣",
"Anguilla":"$",
"Antigua and Barbuda":"$",
"Dominica":"$",
"Grenada":"$",
"Montserrat":"$",
"Saint Kitts and Nevis":"$",
"Saint Lucia":"$",
"Saint Vincent and Grenadine":"$",
"French Polynesia":"₣",
"New Caledonia":"₣",
"Wallis and Futuna":"₣",
"Lesotho":"R",
"Namibia":"R",
"South Africa":"R",
"Yemen":"﷼",
"Zambia":"ZK",
"Zimbabwe":"$",
"Uruguay":"$",
"Uzbekistan":"лв",
"Venezuela":"Bs F",
"Vanuatu":"Vt"
}

currencyBefore = [
"Australia",
"Belgium",
"Cyprus",
"Italy",
"Jamaica",
"New Zealand",
"Portugal",
"Samoa",
"South Korea",
"Tonga",
"Uganda",
"China",
"Hong Kong",
"Denmark",
"Singapore",
"Maldives",
"Netherlands",
"United Kingdom",
"Austria",
"Bangladesh",
"Cambodia",
"Greece",
"Indonesia",
"Jordan",
"Mauritius", 
"Nepal",
"Tanzania", 
"Vietnam",
"Argentina",
"Bahamas",
"Barbados", 
"Bulgaria", 
"Costa Rica",
"Croatia",
"Cuba",
"Czech Republic",
"Dominican Republic",
"Egypt",
"Hungary", 
"Iceland",
"India",
"Ireland",
"Israel", 
"Kenya",
"Madagascar",
"Pakistan",
"Panama",
"Poland",
"Mexico", 
"Morocco", 
"Peru",
"Philippines", 
"Qatar",
"Thailand",
"Tunisia", 
"Ukraine",
"Belize",
"Canada (English)",
"Monaco",
"UAE",
"Afghanistan",
"Albania",
"Armenia",
"Angola",
"Aruba",
"Azerbaijan",
"Bosnia and Herzegovina",
"Bahrain",
"Burundi",
"Bermuda",
"Brunei",
"Bolivia",
"Brazil",
"Bhutan",
"Botswana",
"Belarus",
"Congo",
"Switzerland",
"Lichtenstein",
"Chile",
"Colombia",
"Cape Verde",
"Djibouti",
"Algeria",
"Eritrea",
"Ethiopia",
"Andorra",
"Estonia",
"Kosovo",
"Latvia",
"Lithuania",
"Luxembourg",
"Malta",
"Montenegro",
"San-Marino",
"Slovakia",
"Slovenia",
"Vatican",
"Fiji",
"Georgia",
"South Ossetia",
"Ghana",
"Gibraltar",
"Gambia",
"Guinea",
"Guatemala",
"Guyana",
"Honduras",
"Haiti",
"Palestine",
"Iraq",
"Iran",
"Japan",
"Kyrgyzstan",
"North Korea",
"Kuwait",
"Cayman Islands",
"Kazakhstan",
"Laos",
"Lebanon",
"Sri Lanka",
"Liberia",
"Lesotho",
"Libya",
"Moldova",
"Macedonia",
"Myanmar",
"Mongolia",
"Macao"
"Mauritania",
"Malawi",
"Malaysia",
"Mozambique",
"Namibia",
"Nigeria",
"Nicaragua",
"Cook Islands",
"Niue",
"Pitcairn Island",
"Oman",
"Papua New Guinea",
"Paraguay",
"Romania",
"Kosovo",
"Serbia",
"Russia",
"Rwanda",
"Saudi Arabia",
"Solomon Islands",
"Seychelles",
"Sudan",
"Ascension Island",
"Saint Helena",
"Tristan da Cunha",
"Sierra Leone",
"Somalia",
"Suriname",
"Sao Tome and Principe",
"Syria",
"Swaziland",
"Tajikistan",
"Turkmenistan",
"North Cyprus",
"Turkey",
"Trinidad and Tobago",
"Taiwan",
"American Samoa",
"British Indian Ocean Territory",
"British Virgin Islands",
"Guam",
"Haiti",
"Marshall Islands",
"Micronesia",
"Northern Mariana Islands",
"Pacific Remote islands",
"Palau",
"Panama",
"Puerto Rico",
"Turks and Caicos Islands",
"United States of America",
"US Virgin Islands",
"Benin",
"Burkina Faso",
"Cameroon",
"Central African Republic",
"Chad",
"Congo (Brazzaville)",
"Côte d'Ivoire",
"Equatorial Guinea",
"Gabon",
"Guinea-Bissau",
"Mali",
"Niger",
"Senegal",
"Togo",
"Anguilla",
"Antigua and Barbuda",
"Dominica",
"Grenada",
"Montserrat",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Vincent and Grenadine",
"French Polynesia",
"French Polynesia",
"New Caledonia",
"Wallis and Futuna",
"Lesotho",
"Namibia",
"South Africa",
"Yemen",
"Zambia",
"Zimbabwe",
"Uruguay",
"Uzbekistan",
"Venezuela",
"Vanuatu"
]
currencyAfter = [
"Spain",
"Sweden",
"Finland",
"Norway",
"France",
"Canada (French)",
"Germany",
"Czech Republic",
"Austria",
"Belgium",
"Bulgaria",
"Croatia",
"Cyprus",
"Denmark",
"Estonia",
"Greece",
"Hungary",
"Ireland",
"Italy",
"Latvia",
"Lithuania",
"Luxembourg",
"Malta",
"Netherlands",
"Poland",
"Portugal",
"Romania",
"Slovakia",
"Slovenia",
"Morocco",
"Saudi Arabia",
"Thailand",
"Turkey",
"Vietnam"
]

commaSeparators = [
"France",
"Algeria"
"Albania",
"Andorra",
"Angola",
"Argentina",
"Armenia",
"Austria",
"Azerbaijan",
"Belarus",
"Belgium",
"Bolivia",
"Bosnia and Herzegovina",
"Brazil",
"Bulgaria",
"Cameroon",
"Chile",
"Colombia",
"Costa Rica",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"East Timor",
"Ecuador",
"Estonia",
"Faroes",
"Finland",
"France",
"Germany",
"Georgia",
"Greece",
"Greenland",
"Iceland",
"Indonesia",
"Italy",
"Kazakhstan",
"Kosovo",
"Kyrgyzstan",
"Latvia",
"Lebanon",
"Lithuania",
"Macedonia",
"Moldova",
"Mongolia",
"Morocco",
"Mozambique",
"Namibia",
"Netherlands",
"Norway",
"Paraguay",
"Peru",
"Poland",
"Portugal",
"Romania",
"Russia",
"Serbia",
"Slovakia",
"Slovenia",
"South Africa",
"Spain",
"Sweden",
"Tunisia",
"Turkey",
"Ukraine",
"Uruguay",
"Uzbekistan",
"Venezuela",
"Vietnam"
"Canada (French)",
"Croatia",
"Hungary",
"Switzerland"
    ]

noSubunit = [
    "Japan"
    ]
#Currently no need to manipulate the list, as Japan doesn't tip + users wont need to input anything other than a whole number

myFifths = (".2", ".4", ".6", ".8", ".0")

subUnitOneFifth = [
    "Mauritania", "Madagascar"
    ]
def roundToFifth():
    global bill_amount
    global country
    resolution = 0.2
    if country  in subUnitOneFifth and str(bill_amount).endswith(myFifths) == False:
        print((round (bill_amount / resolution) * resolution))
        print("1/5 function")
    else:
        print("do not")

def oneSf():
    global bill_amount
    bill_amount = format(bill_amount, '.1f')

def twoSf():
    global bill_amount
    global country
    if country not in subUnitOneFifth:
        bill_amount = format(bill_amount, '.2f')
    else:
        oneSf()
        roundToFifth()

def displayBill():
    if country in currencyBefore:
        print(f"your bill is {currencySign[country]}{bill_amount}")
    elif country in currencyAfter:
        print(f"your bill is {bill_amount}{currencySign[country]}")

def makeComma():
    global bill_amount
    if country in commaSeparators:
        bill_amount = str(bill_amount)
        bill_amount = bill_amount.replace(".", ",")
        print(bill_amount)

if country in rounders:
    print(rule[country])
    bill_amount = math.ceil(bill_amount)
    twoSf()
    makeComma()
    displayBill()
    print(f"your new bill is {bill_amount}")
    
elif country in non_tippers:
    twoSf()
    makeComma()
    displayBill()
    print(f"No tip is required here. Your bill is still {bill_amount}")


elif country in rule:
    print(rule[country])
    twoSf()
    makeComma()
    displayBill()
    print(f"Your original bill was {bill_amount}")

elif country in five_percenters:
    bill_amount *= 1.05
    twoSf()
    makeComma()
    displayBill()
    print("your bill is: ", bill_amount)

elif country in ten_percenters:
    bill_amount *= 1.1
    twoSf()
    makeComma()
    displayBill
    print("your bill is: ", bill_amount)


elif country in fifteen_percenters:
    bill_amount *= 1.15
    twoSf()
    makeComma()
    displayBill()
    print("your bill is: ", bill_amount)

else:
    print("That country's tipping information has not yet been added to our database. Please email the developer with any information about a country without data on the list or with any corrections.")